/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_candar_jni_HelloJNI */

#ifndef _Included_dev_candar_jni_HelloJNI
#define _Included_dev_candar_jni_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_candar_jni_HelloJNI
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dev_candar_jni_HelloJNI_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
