/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_candar_jni_CalculateJNI */

#ifndef _Included_dev_candar_jni_CalculateJNI
#define _Included_dev_candar_jni_CalculateJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_candar_jni_CalculateJNI
 * Method:    multiply
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_dev_candar_jni_CalculateJNI_multiply
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
